### ISSUE TITLE
Enable "Re-enroll" edge router feature in ZAC

### ISSUE THREAD

**Issue by rgallettonf** [openziti/ziti-console#338]
The Ziti API support the ability to re-enroll an edge router and create a new enrollment JWT. This should also be made available via the console.

**Comment by qrkourier** [comment]
Yay! This is super useful for in-place recovery of a router that has an expired certificate. It's superior to replacing the router with a new one because policies that grant the replaced router will break even if the replacement has the same name. This way, with re-enroll, the ziti ID is the same, so policies keep working!
